apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsqwen-14b-nscc-ds-4a100-node10-gpu-0-1
  namespace: default
  labels:
    model.aibrix.ai/name: dsqwen-14b
    model.aibrix.ai/port: '8000'
    tre.aibrix.io/managed: 'true'
    tre.aibrix.io/node: nscc-ds-4a100-node10
    tre.aibrix.io/gpu-ids: 0-1
    tre.aibrix.io/routable: 'true'
  annotations: &id001
    tre.aibrix.io/gpu-ids: 0,1
    tre.aibrix.io/gpu-uuids: GPU-71f560a8-e090-c7e6-325f-2e386c08136f,GPU-4bcbcb0c-7eaf-64a1-b3e5-b07cb81d3a96
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsqwen-14b-nscc-ds-4a100-node10-gpu-0-1
  template:
    metadata:
      labels:
        model.aibrix.ai/name: dsqwen-14b
        model.aibrix.ai/port: '8000'
        tre.aibrix.io/managed: 'true'
        tre.aibrix.io/node: nscc-ds-4a100-node10
        tre.aibrix.io/gpu-ids: 0-1
        tre.aibrix.io/routable: 'true'
        app: dsqwen-14b-nscc-ds-4a100-node10-gpu-0-1
      annotations: *id001
    spec:
      nodeName: nscc-ds-4a100-node10
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 20Gi
      - name: models-volume
        hostPath:
          path: /data
      containers:
      - name: vllm-openai
        image: vllm/vllm-openai:0.10.1-sleep
        imagePullPolicy: IfNotPresent
        command:
        - python3
        - -m
        - vllm.entrypoints.openai.api_server
        - --host
        - 0.0.0.0
        - --port
        - '8000'
        - --uvicorn-log-level
        - warning
        - --model
        - /data/nfs_shared_data/Models/DeepSeek-R1-Distill-Qwen-14B
        - --served-model-name
        - dsqwen-14b
        - --enable_sleep_mode
        - --tensor-parallel-size
        - '2'
        - --max-model-len
        - '12288'
        - --gpu-memory-utilization
        - '0.85'
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: GPU-71f560a8-e090-c7e6-325f-2e386c08136f,GPU-4bcbcb0c-7eaf-64a1-b3e5-b07cb81d3a96
        - name: CUDA_VISIBLE_DEVICES
          value: 0,1
        - name: VLLM_SERVER_DEV_MODE
          value: '1'
        - name: VLLM_WORKER_MULTIPROC_METHOD
          value: spawn
        - name: VLLM_USE_MODELSCOPE
          value: 'True'
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: shm
          mountPath: /dev/shm
        - name: models-volume
          mountPath: /data
