apiVersion: v1
kind: Service
metadata:
  name: dsqwen-7b
  namespace: default
  labels:
    model.aibrix.ai/name: dsqwen-7b
spec:
  selector:
    model.aibrix.ai/name: dsqwen-7b
    tre.aibrix.io/routable: 'true'
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
