"""Generate the tre-v2 gpu-truth DaemonSet manifest from the registry.

The agent (``deploy/scripts/gpu_truth_agent.py``) is baked into its own image,
built from ``tre/gpu-truth/Dockerfile`` (build context ``tre/``)::

    docker build -f gpu-truth/Dockerfile -t tre-v2-gpu-truth:<YYYYMMDD>-<sha> .

The image is taken from ``gpu_truth.image`` and the target nodes from
``cluster.nodes[].name`` in ``deploy/registry.yaml`` (the components ignore the
top-level ``gpu_truth:`` section; only this generator reads it). nvidia-smi and
libnvidia-ml come from the host driver through the NVIDIA container runtime
(``NVIDIA_VISIBLE_DEVICES`` + ``NVIDIA_DRIVER_CAPABILITIES=utility``).

Run ``python3 deploy/gen_gpu_truth_manifest.py`` after changing the image or the
nodes (``--interval-s`` / ``--refresh-poll-s`` / ``--ttl-s`` tune the agent
command line; the guard test expects the defaults).
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

DEPLOY_ROOT = Path(__file__).resolve().parent
REGISTRY = DEPLOY_ROOT / "registry.yaml"
MANIFEST = DEPLOY_ROOT / "overlays" / "tre-v2" / "gpu-truth.yaml"

#: Path of the agent inside the image (tre/gpu-truth/Dockerfile).
AGENT_IN_IMAGE = "/app/gpu_truth_agent.py"
#: Keys of the registry ``gpu_truth:`` section.
GPU_TRUTH_KEYS = frozenset({"image"})

_DAEMONSET = """# Generated by tre/deploy/gen_gpu_truth_manifest.py from deploy/registry.yaml
# (gpu_truth.image, cluster.nodes). Do not edit by hand; regenerate with:
#   python3 deploy/gen_gpu_truth_manifest.py
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tre-v2-gpu-truth
  namespace: tre-v2
  labels:
    app.kubernetes.io/name: tre-v2-gpu-truth
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tre-v2-gpu-truth
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tre-v2-gpu-truth
    spec:
      # hostPID stays false: the agent only reads nvidia-smi inside its own
      # container (GPUs injected via NVIDIA_VISIBLE_DEVICES), never the host PID ns.
      hostPID: false
      # Restrict to the TRE GPU nodes (registry cluster.nodes); other GPU nodes
      # in the cluster are out of TRE scope.
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
{node_values}
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: gpu-truth
          # Built from tre/gpu-truth/Dockerfile (python slim + the agent); no
          # CUDA userspace in the image, nvidia-smi / NVML come from the host
          # driver via the NVIDIA container runtime.
          image: {image}
          imagePullPolicy: IfNotPresent
          command:
            - python3
            - {agent}
            - --redis-url
            - redis://tre-v2-redis:6379/0
            - --node
            - $(NODE_NAME)
            - --interval-s
            - "{interval_s}"
            - --refresh-poll-s
            - "{refresh_poll_s}"
            - --ttl-s
            - "{ttl_s}"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            # utility = nvidia-smi + libnvidia-ml only (no compute libraries).
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: utility
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
"""


#: Periodic sample interval (s). The service-manager also asks for a sample on
#: demand before a wake / cold-start headroom gate (tre:gpu_truth_refresh:<node>).
DEFAULT_INTERVAL_S = 10.0
#: How often the agent polls its refresh counter (s); 0 disables refreshes.
DEFAULT_REFRESH_POLL_S = 0.25
#: TTL of tre:gpu_truth:<node>; expiry = truth unavailable (gates fail closed).
DEFAULT_TTL_S = 120


def _num(value: float) -> str:
    return f"{float(value):g}"


def settings_from_registry(raw: dict[str, Any]) -> tuple[str, list[str]]:
    """``(image, node names)`` from a parsed registry.yaml."""
    section = raw.get("gpu_truth") or {}
    if not isinstance(section, dict):
        raise ValueError("gpu_truth: expected a mapping")
    unknown = sorted(set(section) - GPU_TRUTH_KEYS)
    if unknown:
        raise ValueError(f"gpu_truth: unknown keys {unknown} (known: {', '.join(sorted(GPU_TRUTH_KEYS))})")
    image = str(section.get("image") or "").strip()
    if not image:
        raise ValueError("gpu_truth.image is required (the agent image built from tre/gpu-truth/Dockerfile)")
    nodes = [str(node["name"]) for node in ((raw.get("cluster") or {}).get("nodes") or [])]
    if not nodes:
        raise ValueError("cluster.nodes is empty: no node to run the gpu-truth agent on")
    return image, nodes


def render(
    *,
    image: str,
    nodes: list[str],
    interval_s: float = DEFAULT_INTERVAL_S,
    refresh_poll_s: float = DEFAULT_REFRESH_POLL_S,
    ttl_s: int = DEFAULT_TTL_S,
) -> str:
    if interval_s <= 0 or refresh_poll_s < 0 or ttl_s <= interval_s:
        raise ValueError("need interval_s > 0, refresh_poll_s >= 0 and ttl_s > interval_s")
    if not image or not nodes:
        raise ValueError("need an image and at least one node")
    node_values = "\n".join(f"                      - {node}" for node in nodes)
    return _DAEMONSET.format(
        image=image,
        agent=AGENT_IN_IMAGE,
        node_values=node_values,
        interval_s=_num(interval_s),
        refresh_poll_s=_num(refresh_poll_s),
        ttl_s=int(ttl_s),
    )


def render_from_registry(registry_path: Path = REGISTRY, **kwargs: Any) -> str:
    raw = yaml.safe_load(registry_path.read_text(encoding="utf-8")) or {}
    image, nodes = settings_from_registry(raw)
    return render(image=image, nodes=nodes, **kwargs)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--registry", type=Path, default=REGISTRY)
    parser.add_argument("--interval-s", type=float, default=DEFAULT_INTERVAL_S)
    parser.add_argument("--refresh-poll-s", type=float, default=DEFAULT_REFRESH_POLL_S)
    parser.add_argument("--ttl-s", type=int, default=DEFAULT_TTL_S)
    parser.add_argument("--output", type=Path, default=MANIFEST)
    args = parser.parse_args(argv)
    content = render_from_registry(
        args.registry,
        interval_s=args.interval_s,
        refresh_poll_s=args.refresh_poll_s,
        ttl_s=args.ttl_s,
    )
    args.output.write_text(content, encoding="utf-8")
    print(f"wrote {args.output} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
