"""Replay-by-name: loadgen configs and a flat trace tree for the E1 runner.

The runner (``run_arm_pilot.sh``, ``tre/eval/runner``) resolves a trace NAME as
``$ICSE/<NAME>/traces_tre.effective.json`` (+ ``manifest.json`` for the seed) and
``$LOADGEN_CONFIG_ROOT/<NAME>/config.yaml``. NAME = ``<trace>_s<seed>``:

* :func:`write_configs` writes ``<config root>/<trace>/config.yaml`` per spec and a relative
  symlink ``<trace>_s<k> -> <trace>`` per seed in the spec's ``seeds``. The config only
  names the three models and the client (8 processes, 300 s timeout, routing header); its
  ``models[].max_tokens`` is the route-timeout cap and is never used: every request of a
  v2 plan carries its own ``max_output_tokens``.
* :func:`link_names` makes ``<out root>/by-name/<trace>_s<k> -> ../<trace>/seed<k>``, so
  ``ICSE=<out root>/by-name`` (the data tree itself stays ``<trace>/seed<k>``).
"""
from __future__ import annotations

import json
import os
from pathlib import Path

from .capacity import load_capacity

_TEMPLATE = """# Generated by python3 -m tre_replayer.tracegen loadgen-configs from specs/{spec} (do not edit).
# Replay: tre_loadgen_v1 --trace-file <traces-v2 root>/by-name/{trace}_s<k>/traces_tre.effective.json --ignore-eos
# models[].max_tokens = the route-timeout cap; never sent: every request carries its own max_output_tokens.
custom_load_test:
  duration_seconds: {duration}
  gateway_endpoint: "http://localhost:8888"   # ignored: the client needs --base-url
  generate_mode: "custom"
  output:
    base_dir: "./output/traces_v2"
    sub_dir_name: "{trace}"
    files:
      load_timeline_rps: "load_timeline_rps.json"
      load_timeline_token_rate: "load_timeline_token_rate.json"
      trace_data: "traces.json"
      trace_plots: "traces.png"
      performance_metrics: "performance_metrics.json"
      performance_plots: "plot_analysis/"
  random_seed: null
  client:
    api_key: "dummy"
    timeout: 300.0
    enable_streaming: true
    log_level: "INFO"
    routing_algorithm: "least-gpu-cache"
    process_count: 8
    max_coroutines_per_process: 100
    task_batch_window: 5.0
    load_monitor_interval: 1.0
  models:
{models}
  load_mode: "rps"
  total_load: 0
  stable_period: {{min_duration: 30, max_duration: 60}}
  transition_period: {{min_duration: 2, max_duration: 5}}
  noise: {{enabled: false}}
  input_token_config: {{min_length: 32, max_length: 8192, distribution: "normal", mean: 492, std: 0}}
  analysis:
    percentiles: [50, 70, 90, 99]
"""

MODELSCOPE = {"dsllama-8b": "deepseek-ai/DeepSeek-R1-Distill-Llama-8B",
              "dsqwen-7b": "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
              "dsqwen-14b": "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B"}
ORDER = ("dsllama-8b", "dsqwen-7b", "dsqwen-14b")


def _models(spec: dict) -> list[str]:
    real = spec.get("real", {})
    ms = set(spec.get("models", {})) | set(real.get("rho", {})) | set(real.get("v1_factor", {}))
    return [m for m in ORDER if m in ms] + sorted(ms - set(ORDER))


def write_configs(spec_paths, config_root, capacity_path=None) -> list[Path]:
    cap = load_capacity(capacity_path)
    root = Path(config_root)
    written = []
    for sp in spec_paths:
        spec = json.loads(Path(sp).read_text())
        trace = spec["trace"]
        models = "\n".join(
            f'    - name: "{m}"\n      modelscope_url: "{MODELSCOPE.get(m, m)}"\n      max_tokens: {cap.models[m].out_max}'
            for m in _models(spec))
        d = root / trace
        d.mkdir(parents=True, exist_ok=True)
        (d / "config.yaml").write_text(_TEMPLATE.format(spec=Path(sp).name, trace=trace,
                                                        duration=int(spec["duration_s"]), models=models))
        written.append(d / "config.yaml")
        for k in spec.get("seeds", []):
            link = root / f"{trace}_s{k}"
            if link.is_symlink() or link.exists():
                link.unlink()
            os.symlink(trace, link)
    return written


def link_names(out_root) -> list[Path]:
    root = Path(out_root)
    by = root / "by-name"
    by.mkdir(exist_ok=True)
    made = []
    for seed_dir in sorted(root.glob("*/seed*")):
        if seed_dir.parent.name == "by-name" or not (seed_dir / "manifest.json").exists():
            continue
        link = by / f"{seed_dir.parent.name}_s{seed_dir.name[4:]}"
        if link.is_symlink() or link.exists():
            link.unlink()
        os.symlink(os.path.join("..", seed_dir.parent.name, seed_dir.name), link)
        made.append(link)
    return made
