apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - rbac.yaml
  - redis.yaml
  - service-manager.yaml
  - controller.yaml
  - ui.yaml
  - gpu-truth.yaml
