apiVersion: v1
kind: ServiceAccount
metadata:
  name: tre-v2-controller
  namespace: tre-v2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tre-v2-service-manager
  namespace: tre-v2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tre-v2-ui
  namespace: tre-v2
